name: Deploy to VPS
on:
  pull_request:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Install Packages
        run: npm install
      - name: Generate new css
        run: npm run build
      - name: Build and deploy
        run: |
          ssh kronnos@184.168.20.106 "
          sudo su &&
          cd /var/www/html/sigma &&
          git stash &&
          git pull origin master &&
          chmod -R 777 storage/ bootstrap/cache/"
